import { MigrationInterface, QueryRunner } from 'typeorm';

export class CanonicalMvpContract1784303000000 implements MigrationInterface {
  name = 'CanonicalMvpContract1784303000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" ALTER COLUMN "category" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" ADD "user_id" varchar(128) NOT NULL DEFAULT 'legacy'`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" ADD "requested_category" varchar(16)`,
    );
    await queryRunner.query(
      `UPDATE "shopping_runs" SET "requested_category" = COALESCE("category"::text, 'auto')`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" ALTER COLUMN "requested_category" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" ADD "timezone" varchar(32) NOT NULL DEFAULT 'Africa/Cairo'`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" ADD "locale" varchar(5) NOT NULL DEFAULT 'en-EG'`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" ADD "pending_action" jsonb`,
    );
    await queryRunner.query(`ALTER TABLE "shopping_runs" ADD "failure" jsonb`);
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" ADD "browser_expires_at" timestamptz`,
    );
    await queryRunner.query(
      `UPDATE "shopping_runs" SET "browser_expires_at" = "created_at" + interval '1 hour'`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" ALTER COLUMN "browser_expires_at" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" ADD "last_event_id" varchar(128)`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" ADD CONSTRAINT "chk_shopping_runs_timezone_cairo" CHECK ("timezone" = 'Africa/Cairo')`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_shopping_runs_user_status" ON "shopping_runs" ("user_id", "state")`,
    );

    await queryRunner.query(
      `ALTER TABLE "shopping_run_events" DROP CONSTRAINT "uq_shopping_run_events_run_event"`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_run_events" ADD "sequence" bigint GENERATED BY DEFAULT AS IDENTITY`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_run_events" ADD "status" varchar(40)`,
    );
    await queryRunner.query(
      `UPDATE "shopping_run_events" e SET "status" = r."state"::text FROM "shopping_runs" r WHERE r."id" = e."run_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_run_events" ALTER COLUMN "status" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_run_events" ADD CONSTRAINT "uq_shopping_run_events_event_id" UNIQUE ("event_id")`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_shopping_events_run_sequence" ON "shopping_run_events" ("run_id", "sequence")`,
    );

    await queryRunner.query(
      `ALTER TABLE "shopping_merchant_attempts" ADD "merchant_id" varchar(128) NOT NULL DEFAULT 'legacy'`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_merchant_attempts" ADD "category" varchar(16) NOT NULL DEFAULT 'retail'`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_merchant_attempts" ADD "message" text`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_merchant_attempts" ADD "evidence_ids" jsonb NOT NULL DEFAULT '[]'::jsonb`,
    );

    await queryRunner.query(
      `ALTER TABLE "shopping_normalized_offers" ALTER COLUMN "base_price" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_normalized_offers" ALTER COLUMN "final_total" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_normalized_offers" ALTER COLUMN "match_confidence" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_normalized_offers" ADD "merchant_attempt_id" varchar(128) NOT NULL DEFAULT 'legacy'`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_normalized_offers" ADD "merchant_domain" varchar(255) NOT NULL DEFAULT ''`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_normalized_offers" ADD "match" jsonb NOT NULL DEFAULT '{"exact":false,"confidence":0,"explanation":"Legacy offer"}'::jsonb`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_normalized_offers" ADD "price" jsonb NOT NULL DEFAULT '{"itemSubtotal":"0.00","deliveryFee":null,"serviceFee":null,"bookingFee":null,"tax":null,"mandatoryFees":[],"verifiedDiscount":"0.00","optionalTip":null,"finalTotal":null}'::jsonb`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_normalized_offers" ADD "validity" varchar(16) NOT NULL DEFAULT 'incomplete'`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_normalized_offers" ADD "exclusion_reason" text`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_normalized_offers" ADD "incomplete_fields" jsonb NOT NULL DEFAULT '[]'::jsonb`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_shopping_offers_run_validity" ON "shopping_normalized_offers" ("run_id", "validity")`,
    );

    await queryRunner.query(
      `ALTER TABLE "shopping_coupon_attempts" ALTER COLUMN "merchant" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_coupon_attempts" ADD "offer_id" varchar(128) NOT NULL DEFAULT 'legacy'`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_coupon_attempts" ADD "merchant_domain" varchar(255) NOT NULL DEFAULT ''`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_coupon_attempts" ADD "source_url" text NOT NULL DEFAULT 'https://example.invalid/'`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_coupon_attempts" ADD "verified_discount" numeric(12,2) NOT NULL DEFAULT 0`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_coupon_attempts" ADD "rejection_reason" varchar(40)`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_coupon_attempts" ADD "message" text`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_coupon_attempts" ADD "attempted_at" timestamptz`,
    );
    await queryRunner.query(
      `UPDATE "shopping_coupon_attempts" SET "attempted_at" = "created_at"`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_coupon_attempts" ALTER COLUMN "attempted_at" SET NOT NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_shopping_coupons_run_offer" ON "shopping_coupon_attempts" ("run_id", "offer_id")`,
    );

    await queryRunner.query(
      `ALTER TABLE "shopping_run_approvals" ADD "request_id" varchar(128) NOT NULL DEFAULT 'legacy'`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_run_approvals" ADD "offer_id" varchar(128)`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_run_approvals" ADD "status" varchar(16) NOT NULL DEFAULT 'approved'`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_run_approvals" ADD "expires_at" timestamptz`,
    );

    await queryRunner.query(
      `ALTER TABLE "shopping_evidence_artifacts" ADD "captured_at" timestamptz`,
    );
    await queryRunner.query(
      `UPDATE "shopping_evidence_artifacts" SET "captured_at" = "created_at"`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_evidence_artifacts" ALTER COLUMN "captured_at" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_evidence_artifacts" ADD "merchant_attempt_id" varchar(128)`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_evidence_artifacts" ADD "redacted" boolean NOT NULL DEFAULT true`,
    );

    await queryRunner.query(
      `CREATE TABLE "shopping_control_leases" ("id" varchar(26) NOT NULL, "created_at" timestamp NOT NULL DEFAULT now(), "updated_at" timestamp NOT NULL DEFAULT now(), "deleted_at" timestamp, "run_id" varchar(26) NOT NULL, "holder_user_id" varchar(128) NOT NULL, "status" varchar(16) NOT NULL, "claimed_at" timestamptz NOT NULL, "renewed_at" timestamptz NOT NULL, "expires_at" timestamptz NOT NULL, CONSTRAINT "pk_shopping_control_leases" PRIMARY KEY ("id"), CONSTRAINT "fk_shopping_control_leases_run" FOREIGN KEY ("run_id") REFERENCES "shopping_runs"("id") ON DELETE CASCADE)`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_shopping_control_leases_run_status" ON "shopping_control_leases" ("run_id", "status")`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_shopping_active_control_lease" ON "shopping_control_leases" ("run_id") WHERE "status" = 'active'`,
    );

    await queryRunner.query(
      `CREATE TABLE "shopping_idempotency_records" ("id" varchar(26) NOT NULL, "created_at" timestamp NOT NULL DEFAULT now(), "updated_at" timestamp NOT NULL DEFAULT now(), "deleted_at" timestamp, "principal_id" varchar(128) NOT NULL, "method" varchar(8) NOT NULL, "path" varchar(512) NOT NULL, "key" varchar(128) NOT NULL, "request_hash" varchar(64) NOT NULL, "response" jsonb NOT NULL, "expires_at" timestamptz NOT NULL, CONSTRAINT "pk_shopping_idempotency_records" PRIMARY KEY ("id"), CONSTRAINT "uq_shopping_idempotency_scope" UNIQUE ("principal_id", "method", "path", "key"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_shopping_idempotency_expires" ON "shopping_idempotency_records" ("expires_at")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "shopping_idempotency_records"`);
    await queryRunner.query(`DROP TABLE "shopping_control_leases"`);
    await queryRunner.query(
      `ALTER TABLE "shopping_evidence_artifacts" DROP COLUMN "redacted", DROP COLUMN "merchant_attempt_id", DROP COLUMN "captured_at"`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_run_approvals" DROP COLUMN "expires_at", DROP COLUMN "status", DROP COLUMN "offer_id", DROP COLUMN "request_id"`,
    );
    await queryRunner.query(`DROP INDEX "idx_shopping_coupons_run_offer"`);
    await queryRunner.query(
      `UPDATE "shopping_coupon_attempts" SET "merchant" = '' WHERE "merchant" IS NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_coupon_attempts" ALTER COLUMN "merchant" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_coupon_attempts" DROP COLUMN "attempted_at", DROP COLUMN "message", DROP COLUMN "rejection_reason", DROP COLUMN "verified_discount", DROP COLUMN "source_url", DROP COLUMN "merchant_domain", DROP COLUMN "offer_id"`,
    );
    await queryRunner.query(`DROP INDEX "idx_shopping_offers_run_validity"`);
    await queryRunner.query(
      `UPDATE "shopping_normalized_offers" SET "base_price" = 0, "final_total" = 0, "match_confidence" = 0 WHERE "base_price" IS NULL OR "final_total" IS NULL OR "match_confidence" IS NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_normalized_offers" ALTER COLUMN "base_price" SET NOT NULL, ALTER COLUMN "final_total" SET NOT NULL, ALTER COLUMN "match_confidence" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_normalized_offers" DROP COLUMN "incomplete_fields", DROP COLUMN "exclusion_reason", DROP COLUMN "validity", DROP COLUMN "price", DROP COLUMN "match", DROP COLUMN "merchant_domain", DROP COLUMN "merchant_attempt_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_merchant_attempts" DROP COLUMN "evidence_ids", DROP COLUMN "message", DROP COLUMN "category", DROP COLUMN "merchant_id"`,
    );
    await queryRunner.query(`DROP INDEX "idx_shopping_events_run_sequence"`);
    await queryRunner.query(
      `ALTER TABLE "shopping_run_events" DROP CONSTRAINT "uq_shopping_run_events_event_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_run_events" DROP COLUMN "status", DROP COLUMN "sequence"`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_run_events" ADD CONSTRAINT "uq_shopping_run_events_run_event" UNIQUE ("run_id", "event_id")`,
    );
    await queryRunner.query(`DROP INDEX "idx_shopping_runs_user_status"`);
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" DROP CONSTRAINT "chk_shopping_runs_timezone_cairo"`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" DROP COLUMN "last_event_id", DROP COLUMN "browser_expires_at", DROP COLUMN "failure", DROP COLUMN "pending_action", DROP COLUMN "locale", DROP COLUMN "timezone", DROP COLUMN "requested_category", DROP COLUMN "user_id"`,
    );
    await queryRunner.query(
      `UPDATE "shopping_runs" SET "category" = 'retail' WHERE "category" IS NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "shopping_runs" ALTER COLUMN "category" SET NOT NULL`,
    );
  }
}
