export const MVP_AUDIT_ACTIONS = {
  AUTHENTICATION_SESSION_REVOKED: 'authentication_session.revoked',
  ORGANIZATION_CREATED: 'organization.created',
  ORGANIZATION_MEMBERSHIP_CREATED: 'organization_membership.created',
  ORGANIZATION_MEMBERSHIP_TRANSITIONED: 'organization_membership.transitioned',
  PROJECT_CREATED: 'project.created',
  PROJECT_TRANSITIONED: 'project.transitioned',
  ENVIRONMENT_CREATED: 'environment.created',
  ENVIRONMENT_VERSION_CREATED: 'environment_version.created',
  ENVIRONMENT_VERIFICATION_DECIDED: 'environment_verification.decided',
  TARGET_CREATED: 'target.created',
  TARGET_VERSION_CREATED: 'target_version.created',
  TARGET_VERIFICATION_DECIDED: 'target_verification.decided',
  APPLICATION_ROLE_CREATED: 'application_role.created',
  APPLICATION_ROLE_TRANSITIONED: 'application_role.transitioned',
  CREDENTIAL_HANDLE_REGISTERED: 'credential_handle.registered',
  CREDENTIAL_HANDLE_REVOKED: 'credential_handle.revoked',
  FIXTURE_CREATED: 'fixture.created',
  FIXTURE_VERSION_CREATED: 'fixture_version.created',
  FIXTURE_VERSION_REVIEWED: 'fixture_version.reviewed',
  FIXTURE_SETUP: 'fixture.setup',
  FIXTURE_CLEANUP: 'fixture.cleanup',
  CAMPAIGN_CREATED: 'campaign.created',
  CAMPAIGN_TRANSITIONED: 'campaign.transitioned',
  CAMPAIGN_PLANNING_REQUESTED: 'campaign_planning.requested',
  REQUIREMENT_SOURCE_CREATED: 'requirement_source.created',
  REQUIREMENT_SOURCE_TRANSITIONED: 'requirement_source.transitioned',
  REQUIREMENT_SOURCE_INGESTED: 'requirement_source.ingested',
  REQUIREMENT_VERSION_CREATED: 'requirement_version.created',
  REQUIREMENT_VERSION_REVIEWED: 'requirement_version.reviewed',
  DISCOVERY_CREATED: 'discovery.created',
  PLAN_CREATED: 'plan.created',
  PLAN_VERSION_REVIEWED: 'plan_version.reviewed',
  CAMPAIGN_PROFILE_CREATED: 'campaign_profile.created',
  CAMPAIGN_PROFILE_VERSION_CREATED: 'campaign_profile_version.created',
  CAMPAIGN_BUDGET_RESERVED: 'campaign_budget.reserved',
  CAMPAIGN_BUDGET_RELEASED: 'campaign_budget.released',
  FINDING_ASSIGNED: 'finding.assigned',
  FINDING_COMMENTED: 'finding.commented',
  FINDING_EXPECTED_BEHAVIOR_MARKED: 'finding.expected_behavior_marked',
  FINDING_FIX_CLAIM_CREATED: 'finding_fix_claim.created',
  FINDING_RETEST_REQUESTED: 'finding_retest.requested',
  FINDING_CLOSED: 'finding.closed',
  FINDING_RISK_ACCEPTANCE_CREATED: 'finding_risk_acceptance.created',
  FINDING_RISK_ACCEPTANCE_REVOKED: 'finding_risk_acceptance.revoked',
  CAMPAIGN_EXPORT_CREATED: 'campaign_export.created',
  CAMPAIGN_FINAL_RESULT_FINALIZED: 'campaign_final_result.finalized',
  RUN_CREATED: 'run.created',
  RUN_CONTROL_ACQUIRED: 'run_control.acquired',
  RUN_CONTROL_RELEASED: 'run_control.released',
  RUN_CANCELLED: 'run.cancelled',
} as const;

export type AuditAction =
  (typeof MVP_AUDIT_ACTIONS)[keyof typeof MVP_AUDIT_ACTIONS];
